// REGISTRAR USUARIO
export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"
// LOGIN USUARIO
export const LOGIN_USUARIO = "LOGIN_USUARIO"
export const LOGIN_USUARIO_SUCCESS = "LOGIN_USUARIO_SUCCESS"
export const LOGIN_USUARIO_ERROR = "LOGIN_USUARIO_ERROR"
// CREAR RECURSO
export const CREATE_RESOURCE = "CREATE_RESOURCE"
export const CREATE_RESOURCE_SUCCESS = "CREATE_RESOURCE_SUCCESS"
export const CREATE_RESOURCE_ERROR = "CREATE_RESOURCE_ERROR"
// OBTENER MIS RECURSOS
export const GET_MY_RESOURCES = "GET_MY_RESOURCES"
export const GET_MY_RESOURCES_SUCCESS = "GET_MY_RESOURCES_SUCCESS"
export const GET_MY_RESOURCES_ERROR = "GET_MY_RESOURCES_ERROR"
// CERRAR SESION
export const CERRAR_SESION = "CERRAR_SESION";
// OBTENER RECURSOS PENDIENTES
export const GET_PENDING_RESOURCES = "GET_PENDING_RESOURCES"
export const GET_PENDING_RESOURCES_SUCCESS = "GET_PENDING_RESOURCES_SUCCESS"
export const GET_PENDING_RESOURCES_ERROR = "GET_PENDING_RESOURCES_ERROR"
// CAMBIAR ESTADO DE RECURSO
export const UPDATE_CONDITION = "UPDATE_CONDITION"
export const UPDATE_CONDITION_SUCCESS = "UPDATE_CONDITION_SUCCESS"
export const UPDATE_CONDITION_ERROR = "UPDATE_CONDITION_ERROR"
// CHANGE SINGLE RESOURCE
export const CHANGE_SINGLE_RESOURCE = "CHANGE_SINGLE_RESOURCE"

// OBTENER RECURSOS RECIENTES
export const GET_RECENT_RESOURCES = "GET_RECENT_RESOURCES"
export const GET_RECENT_RESOURCES_SUCCESS = "GET_RECENT_RESOURCES_SUCCESS"
export const GET_RECENT_RESOURCES_ERROR = "GET_RECENT_RESOURCES_ERROR"
// OBTENER RECURSOS RECOMENDADOS
export const GET_RECOMMENDED_RESOURCES = "GET_RECOMMENDED_RESOURCES"
export const GET_RECOMMENDED_RESOURCES_SUCCESS = "GET_RECOMMENDED_RESOURCES_SUCCESS"
export const GET_RECOMMENDED_RESOURCES_ERROR = "GET_RECOMMENDED_RESOURCES_ERROR"
// OBTENER RECURSOS MÁS VALORADOS
export const GET_MORE_CALIFICATION_RESOURCES = "GET_MORE_CALIFICATION_RESOURCES"
export const GET_MORE_CALIFICATION_RESOURCES_SUCCESS = "GET_MORE_CALIFICATION_RESOURCES_SUCCESS"
export const GET_MORE_CALIFICATION_RESOURCES_ERROR = "GET_MORE_CALIFICATION_RESOURCES_ERROR"
// CREAR USUARIOS
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_ERROR = "CREATE_USER_ERROR"
// ACTUALIZAR RECURSOS 
export const UPDATE_RESOURCE = "UPDATE_RESOURCE";
export const UPDATE_RESOURCE_SUCCESS = "UPDATE_RESOURCE_SUCCESS"
export const UPDATE_RESOURCE_ERROR = "UPDATE_RESOURCE_ERROR"
// AGREGAR COMENTARIO
export const COMMENT_RESOURCE = "COMMENT_RESOURCE";
export const COMMENT_RESOURCE_SUCCESS = "COMMENT_RESOURCE_SUCCESS"
export const COMMENT_RESOURCE_ERROR = "COMMENT_RESOURCE_ERROR"
// FILTRAR PO ESPECIALIDAD
export const FILTER_SPECIALTY = "FILTER_SPECIALTY";
export const FILTER_SPECIALTY_SUCCESS = "FILTER_SPECIALTY_SUCCESS";
export const FILTER_SPECIALTY_ERROR = "FILTER_SPECIALTY_ERROR";
// OBTENER RECURSOS CON TAGS IGUALES
export const GET_TAGS_IGUALES = "GET_TAGS_IGUALES";
export const GET_TAGS_IGUALES_SUCCESS = "GET_TAGS_IGUALES_SUCCESS";
export const GET_TAGS_IGUALES_ERROR = "GET_TAGS_IGUALES_ERROR";
// BORRAR RECURSO
export const DELETE_RESOURCES = "DELETE_RESOURCES";
export const DELETE_RESOURCES_SUCCESS = "DELETE_RESOURCES_SUCCESS";
export const DELETE_RESOURCES_ERROR = "DELETE_RESOURCES_ERROR";
// BUSQUEDA DE MOTOR
export const GET_FIND_MOTOR = "GET_FIND_MOTOR";
export const GET_FIND_MOTOR_SUCCESS = "GET_FIND_MOTOR_SUCCESS";
export const GET_FIND_MOTOR_ERROR = "GET_FIND_MOTOR_ERROR";
// OBTENER RECURSO POR ID
export const GET_ID_RESOURCE = "GET_ID_RESOURCE";
export const GET_ID_RESOURCE_SUCCESS = "GET_ID_RESOURCE_SUCCESS";
export const GET_ID_RESOURCE_ERROR = "GET_ID_RESOURCE_ERROR";

