// REGISTRAR USUARIO
export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"
// LOGIN USUARIO
export const LOGIN_USUARIO = "LOGIN_USUARIO"
export const LOGIN_USUARIO_SUCCESS = "LOGIN_USUARIO_SUCCESS"
export const LOGIN_USUARIO_ERROR = "LOGIN_USUARIO_ERROR"
// CREAR RECURSO
export const CREATE_RESOURCE = "CREATE_RESOURCE"
export const CREATE_RESOURCE_SUCCESS = "CREATE_RESOURCE_SUCCESS"
export const CREATE_RESOURCE_ERROR = "CREATE_RESOURCE_ERROR"
// OBTENER MIS RECURSOS
export const GET_MY_RESOURCES = "GET_MY_RESOURCES"
export const GET_MY_RESOURCES_SUCCESS = "GET_MY_RESOURCES_SUCCESS"
export const GET_MY_RESOURCES_ERROR = "GET_MY_RESOURCES_ERROR"
// CERRAR SESION
export const CERRAR_SESION = "CERRAR_SESION";
// OBTENER RECURSOS PENDIENTES
export const GET_PENDING_RESOURCES = "GET_PENDING_RESOURCES"
export const GET_PENDING_RESOURCES_SUCCESS = "GET_PENDING_RESOURCES_SUCCESS"
export const GET_PENDING_RESOURCES_ERROR = "GET_PENDING_RESOURCES_ERROR"
// CAMBIAR ESTADO DE RECURSO
export const UPDATE_CONDITION = "UPDATE_CONDITION"
export const UPDATE_CONDITION_SUCCESS = "UPDATE_CONDITION_SUCCESS"
export const UPDATE_CONDITION_ERROR = "UPDATE_CONDITION_ERROR"
// CHANGE SINGLE RESOURCE
export const CHANGE_SINGLE_RESOURCE = "CHANGE_SINGLE_RESOURCE"

// OBTENER RECURSOS RECIENTES
export const GET_RECENT_RESOURCES = "GET_RECENT_RESOURCES"
export const GET_RECENT_RESOURCES_SUCCESS = "GET_RECENT_RESOURCES_SUCCESS"
export const GET_RECENT_RESOURCES_ERROR = "GET_RECENT_RESOURCES_ERROR"
// OBTENER RECURSOS MÁS VALORADOS
export const GET_MORE_CALIFICATION_RESOURCES = "GET_MORE_CALIFICATION_RESOURCES"
export const GET_MORE_CALIFICATION_RESOURCES_SUCCESS = "GET_MORE_CALIFICATION_RESOURCES_SUCCESS"
export const GET_MORE_CALIFICATION_RESOURCES_ERROR = "GET_MORE_CALIFICATION_RESOURCES_ERROR"
